version: "3.8"
services:
  api:
    build:
      context: ./api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - db
    restart: always
  db:
    image: mysql
    ports:
      - 3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
  nginx:
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - db
      - api
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
